import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getProducts } from '@/lib/shopify';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1 className="text-xl font-bold text-red-600">{data.shop.name}</h1>
        <p className="text-gray-600 text-sm">{data.shop.description}</p>
        {children}
      </body>
    </html>
  );
}
