import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import ClientProviders from "../components/layout/ClientProviders";
import "./globals.css";

import AnnouncementBar from "@/components/layout/AnnouncementBar";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body className="antialiased font-sans">
        <ClientProviders>
          <AnnouncementBar />
          <Header />
          {children}
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}
